# Generated by Django 3.2.7 on 2021-10-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('rating', models.IntegerField(default=5)),
                ('poster_url', models.URLField()),
                ('synopsis', models.TextField()),
                ('cast', models.TextField()),
            ],
        ),
    ]
